<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114150437 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add users and login_codes tables, link daily_notes to user';
    }

    public function up(Schema $schema): void
    {
        // Create users table
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');

        // Create login_codes table
        $this->addSql('CREATE TABLE login_codes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(6) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, attempts INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E3DD06D9A76ED395 ON login_codes (user_id)');
        $this->addSql('ALTER TABLE login_codes ADD CONSTRAINT FK_E3DD06D9A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');

        // Drop old unique constraint on date only
        $this->addSql('DROP INDEX IF EXISTS uniq_813ac758aa9e377a');

        // Add user_id column as nullable first
        $this->addSql('ALTER TABLE daily_notes ADD user_id INT');

        // Create default user and migrate existing data
        $this->addSql("INSERT INTO users (email, created_at, updated_at) VALUES ('default@dopaminder.local', NOW(), NOW())");
        $this->addSql('UPDATE daily_notes SET user_id = (SELECT id FROM users WHERE email = \'default@dopaminder.local\') WHERE user_id IS NULL');

        // Set NOT NULL constraint
        $this->addSql('ALTER TABLE daily_notes ALTER COLUMN user_id SET NOT NULL');

        // Add foreign key and indexes
        $this->addSql('ALTER TABLE daily_notes ADD CONSTRAINT FK_813AC758A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_813AC758A76ED395 ON daily_notes (user_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_date ON daily_notes (user_id, date)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE login_codes DROP CONSTRAINT FK_E3DD06D9A76ED395');
        $this->addSql('DROP TABLE login_codes');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE daily_notes DROP CONSTRAINT FK_813AC758A76ED395');
        $this->addSql('DROP INDEX IDX_813AC758A76ED395');
        $this->addSql('DROP INDEX unique_user_date');
        $this->addSql('ALTER TABLE daily_notes DROP user_id');
        $this->addSql('CREATE UNIQUE INDEX uniq_813ac758aa9e377a ON daily_notes (date)');
    }
}
