<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120085320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create time_block_exceptions table for per-day overrides to time blocks';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE time_block_exceptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exception_date DATE NOT NULL, is_skipped BOOLEAN DEFAULT false NOT NULL, override_start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, override_end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, time_block_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6AF91AA4D68C1C0 ON time_block_exceptions (time_block_id)');
        $this->addSql('CREATE UNIQUE INDEX time_block_date_unique ON time_block_exceptions (time_block_id, exception_date)');
        $this->addSql('ALTER TABLE time_block_exceptions ADD CONSTRAINT FK_D6AF91AA4D68C1C0 FOREIGN KEY (time_block_id) REFERENCES time_blocks (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE time_block_exceptions DROP CONSTRAINT FK_D6AF91AA4D68C1C0');
        $this->addSql('DROP TABLE time_block_exceptions');
    }
}
