<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113125148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE daily_notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, raw_content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_813AC758AA9E377A ON daily_notes (date)');
        $this->addSql('CREATE TABLE events (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, date DATE NOT NULL, daily_note_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5387574AF90CD9A1 ON events (daily_note_id)');
        $this->addSql('CREATE TABLE journal_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, daily_note_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FD43FD20F90CD9A1 ON journal_entries (daily_note_id)');
        $this->addSql('CREATE TABLE notes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, daily_note_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_11BA68CF90CD9A1 ON notes (daily_note_id)');
        $this->addSql('CREATE TABLE tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, is_completed BOOLEAN NOT NULL, due_date DATE DEFAULT NULL, category VARCHAR(255) NOT NULL, daily_note_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50586597F90CD9A1 ON tasks (daily_note_id)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574AF90CD9A1 FOREIGN KEY (daily_note_id) REFERENCES daily_notes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE journal_entries ADD CONSTRAINT FK_FD43FD20F90CD9A1 FOREIGN KEY (daily_note_id) REFERENCES daily_notes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notes ADD CONSTRAINT FK_11BA68CF90CD9A1 FOREIGN KEY (daily_note_id) REFERENCES daily_notes (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_50586597F90CD9A1 FOREIGN KEY (daily_note_id) REFERENCES daily_notes (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE events DROP CONSTRAINT FK_5387574AF90CD9A1');
        $this->addSql('ALTER TABLE journal_entries DROP CONSTRAINT FK_FD43FD20F90CD9A1');
        $this->addSql('ALTER TABLE notes DROP CONSTRAINT FK_11BA68CF90CD9A1');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_50586597F90CD9A1');
        $this->addSql('DROP TABLE daily_notes');
        $this->addSql('DROP TABLE events');
        $this->addSql('DROP TABLE journal_entries');
        $this->addSql('DROP TABLE notes');
        $this->addSql('DROP TABLE tasks');
    }
}
