<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116085355 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE check_ins (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, stats_done INT DEFAULT 0 NOT NULL, stats_tomorrow INT DEFAULT 0 NOT NULL, stats_today INT DEFAULT 0 NOT NULL, stats_dropped INT DEFAULT 0 NOT NULL, stats_overdue_cleared INT DEFAULT 0 NOT NULL, best_combo INT DEFAULT 0 NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DFFFC3DFA76ED395 ON check_ins (user_id)');
        $this->addSql('CREATE INDEX idx_check_ins_user_date ON check_ins (user_id, date)');
        $this->addSql('ALTER TABLE check_ins ADD CONSTRAINT FK_DFFFC3DFA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tasks ADD is_dropped BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE tasks ADD completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD check_in_interval VARCHAR(20) DEFAULT \'3h\' NOT NULL');
        $this->addSql('ALTER TABLE users ADD zen_mode BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE users ADD sound_enabled BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE check_ins DROP CONSTRAINT FK_DFFFC3DFA76ED395');
        $this->addSql('DROP TABLE check_ins');
        $this->addSql('ALTER TABLE tasks DROP is_dropped');
        $this->addSql('ALTER TABLE tasks DROP completed_at');
        $this->addSql('ALTER TABLE users DROP check_in_interval');
        $this->addSql('ALTER TABLE users DROP zen_mode');
        $this->addSql('ALTER TABLE users DROP sound_enabled');
    }
}
