<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120070610 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create time_blocks table and time_block_tags join table for TimeBlock entity';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE time_blocks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(7) NOT NULL, start_time TIME(0) WITHOUT TIME ZONE NOT NULL, end_time TIME(0) WITHOUT TIME ZONE NOT NULL, recurrence_type VARCHAR(255) NOT NULL, recurrence_days JSON DEFAULT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_971BDA8EA76ED395 ON time_blocks (user_id)');
        $this->addSql('CREATE TABLE time_block_tags (time_block_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (time_block_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_2148EAB04D68C1C0 ON time_block_tags (time_block_id)');
        $this->addSql('CREATE INDEX IDX_2148EAB0BAD26311 ON time_block_tags (tag_id)');
        $this->addSql('ALTER TABLE time_blocks ADD CONSTRAINT FK_971BDA8EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE time_block_tags ADD CONSTRAINT FK_2148EAB04D68C1C0 FOREIGN KEY (time_block_id) REFERENCES time_blocks (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_block_tags ADD CONSTRAINT FK_2148EAB0BAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE time_blocks DROP CONSTRAINT FK_971BDA8EA76ED395');
        $this->addSql('ALTER TABLE time_block_tags DROP CONSTRAINT FK_2148EAB04D68C1C0');
        $this->addSql('ALTER TABLE time_block_tags DROP CONSTRAINT FK_2148EAB0BAD26311');
        $this->addSql('DROP TABLE time_blocks');
        $this->addSql('DROP TABLE time_block_tags');
    }
}
