<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260118104001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(7) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FBC9426A76ED395 ON tags (user_id)');
        $this->addSql('CREATE TABLE task_tags (task_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (task_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_1C0F005D8DB60186 ON task_tags (task_id)');
        $this->addSql('CREATE INDEX IDX_1C0F005DBAD26311 ON task_tags (tag_id)');
        $this->addSql('ALTER TABLE tags ADD CONSTRAINT FK_6FBC9426A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_tags ADD CONSTRAINT FK_1C0F005D8DB60186 FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task_tags ADD CONSTRAINT FK_1C0F005DBAD26311 FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tags DROP CONSTRAINT FK_6FBC9426A76ED395');
        $this->addSql('ALTER TABLE task_tags DROP CONSTRAINT FK_1C0F005D8DB60186');
        $this->addSql('ALTER TABLE task_tags DROP CONSTRAINT FK_1C0F005DBAD26311');
        $this->addSql('DROP TABLE tags');
        $this->addSql('DROP TABLE task_tags');
    }
}
