<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260117183933 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE recurring_tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(500) NOT NULL, recurrence_type VARCHAR(255) NOT NULL, recurrence_days JSON DEFAULT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, last_generated_date DATE DEFAULT NULL, category VARCHAR(255) NOT NULL, estimated_minutes INT DEFAULT NULL, fixed_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A47A8C8A76ED395 ON recurring_tasks (user_id)');
        $this->addSql('ALTER TABLE recurring_tasks ADD CONSTRAINT FK_3A47A8C8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tasks ADD recurring_task_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_505865975540940F FOREIGN KEY (recurring_task_id) REFERENCES recurring_tasks (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_505865975540940F ON tasks (recurring_task_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recurring_tasks DROP CONSTRAINT FK_3A47A8C8A76ED395');
        $this->addSql('DROP TABLE recurring_tasks');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_505865975540940F');
        $this->addSql('DROP INDEX IDX_505865975540940F');
        $this->addSql('ALTER TABLE tasks DROP recurring_task_id');
    }
}
